### ISSUE TITLE
base2.DOM.bind() breaks jQuery

### ISSUE THREAD

**Issue by bit4fox** [scoutnet/plugins.typo3.sh_scoutnet_kalender#1]
Auf der Startseite von ScoutNet funktioniert kluft_switcher.js nicht, weil sich base2 und jQuery in die Haare kriegen. Können wir auf base2 verzichten? Das bricht ja so auch die Skripte auf Drittseiten.

**Comment by sHorst** [comment]
ich habe es aus dem js entfernt. es muss jetzt das js noch so angepasst werden, das die funktionalität mit jquery tut.
